version: '3.8'
services:
    payment_request_service:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8001:8000
      volumes:
        - .:/app
        - ../database:/app/database
