# Generated by Django 3.2.10 on 2021-12-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_currency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='transaction_id',
            field=models.CharField(default=129475833, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
