# Generated by Django 3.2.10 on 2021-12-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_paymentrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.paymentrequest', unique=True),
        ),
    ]
